# For more details on the format and content:
# https://github.com/robocorp/rcc/blob/master/docs/recipes.md#what-is-in-condayaml
# Tip: Adding a link to the release notes of the packages helps maintenance and security.
channels:
  - conda-forge
dependencies:
  # Define conda-forge packages here -> https://anaconda.org/search
  # When available, prefer the conda-forge packages over pip as installations are more efficient.
  - python=3.9.13                     # https://pyreadiness.org/3.9/
  - nodejs=20.9.0                    # https://github.com/nodejs/node/blob/main/CHANGELOG.md
  - pip=24.0                   # https://pip.pypa.io/en/stable/news/
  - pip:
    # Define pip packages here -> https://pypi.org/
    - robotframework-browser==18.1.0  # https://github.com/MarketSquare/robotframework-browser/releases
    - rpaframework==28.2.0            # https://rpaframework.org/releasenotes.html
    - azure.core==1.30.0
    - azure.ai.formrecognizer==3.3.2
    - openai==1.12.0
rccPostInstall:
  - rfbrowser init                    # Initialize Playwright